### ISSUE TITLE
Mention supported APP4MC version in the docs

### ISSUE THREAD

**Issue by Boschindi** [inchron/am2inc#1]
Hi,
I would really look forward to track the supported APP4MC version here. I was not able to find it in the documentation. Can you help me out where to find it?

**Comment by mdoerfel** [comment]
You are right, this information is missing in the README, we will add it.

Currently, all Amalthea versions from 1.2.0 to 3.3.0 are supported. Depending on the version of the input model, the generated amalthea library and the converter are selected. The version of the created inchron model is fixed.

When you use the CLI option `-V`, am2inc dumps the supported versions:

```
$ am2inc -V
Version 3.3.0 Build Aug 28 2024 (bc68646)
Amalthea : http://app4mc.eclipse.org/amalthea/1.2.0
           http://app4mc.eclipse.org/amalthea/2.0.0
           http://app4mc.eclipse.org/amalthea/2.1.0
           http://app4mc.eclipse.org/amalthea/2.2.0
           http://app4mc.eclipse.org/amalthea/3.0.0
           http://app4mc.eclipse.org/amalthea/3.1.0
           http://app4mc.eclipse.org/amalthea/3.2.0
           http://app4mc.eclipse.org/amalthea/3.3.0
INCHRON  : http://inchron.com/realtime/root/3.5.0

version: 3.5.0
capabilities: +multi
```

This repository is intended for users who want to change the model conversion. If you want to stick with the standard behavior, we also offer prebuilt installers. You can contact us at [support@inchron.com](mailto:support@inchron.com).

**Comment by Boschindi** [comment]
Great! Thanks for the answer.
